version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: autoatende-postgres
    restart: always
    environment:
      POSTGRES_USER: echat
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: echat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: autoatende-redis
    restart: always
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
